apiVersion: apps/v1
kind: Deployment
metadata:
  name: flybits-application
spec:
  selector:
    matchLabels:
      app: flybits-application
  replicas: 4
  template:
    metadata:
      labels:
        app: flybits-application
    spec:
      containers:
      - name: nginx
        image: nginx:1.18-alpine
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: flybits-application-service
spec:
  selector:
    app: flybits-application
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80