apiVersion: apps/v1
kind: Deployment
metadata:
  name: flybits-application
spec:
  selector:
    matchLabels:
      app: flybits-application
  replicas: 4
  template:
    metadata:
      labels:
        app: flybits-application
    spec:
      volumes:
        - name: logs
          emptyDir: {}
      containers:
        - name: nginx
          image: nginx:1.19-alpine
          ports:
          - containerPort: 80
          volumeMounts:
            - name: logs
              mountPath: /var/log/nginx
        - name: redis
          image: redis:alpine
          ports:
          - containerPort: 6379
          volumeMounts:
            - name: logs
              mountPath: /var/log
      initContainers:
        - name: init-flybits-application
          image: alpine:3
          command: ["sh", "-c", "sleep 30"]
---
apiVersion: v1
kind: Service
metadata:
  name: flybits-application-service
spec:
  selector:
    app: flybits-application
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flybits-application-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: flybits-application-service
            port:
              number: 80